name: CI

on:
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_10.3.app/Contents/Developer'
    - name: XCTest
      run: xcodebuild test -scheme GithubUsers-iOS -configuration Debug
    - name: Build # シミュレーター向け
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
